/**
 Auto-generated by: angular-three-plugin:gltf
 */

import type * as THREE from 'three';
import { Group, Mesh } from 'three';
import { extend, type NgtThreeElements, NgtElementEvents, NgtObjectEvents } from 'angular-three';
import {
  Component,
  ChangeDetectionStrategy,
  CUSTOM_ELEMENTS_SCHEMA,
  input,
  viewChild,
  ElementRef,
  inject,
} from '@angular/core';
import { gltfResource } from 'angular-three-soba/loaders';
import type { GLTF } from 'three-stdlib';

// @ts-expect-error - import .glb/.gltf file
import PokerDiceGLTF from '../../../../public/assets/dice.glb' with { loader: 'file' };

gltfResource.preload(PokerDiceGLTF);

export type PokerDiceGLTFGLTFResult = GLTF & {
  nodes: {
    Cube: THREE.Mesh;
  };
  materials: {
    Material: THREE.MeshStandardMaterial;
  };
};

@Component({
  selector: 'app-poker-dice',
  template: `
    @if (gltf.value(); as gltf) {
      @let nodes = gltf.nodes;
      @let materials = gltf.materials;

      <ngt-group #model [parameters]="options()" [dispose]="null">
        <ngt-mesh [geometry]="nodes.Cube.geometry" [material]="materials.Material" />

        <ng-content />
      </ngt-group>
    }
  `,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  changeDetection: ChangeDetectionStrategy.OnPush,
  hostDirectives: [
    {
      directive: NgtObjectEvents,
      outputs: [
        'click',
        'dblclick',
        'contextmenu',
        'pointerup',
        'pointerdown',
        'pointerover',
        'pointerout',
        'pointerenter',
        'pointerleave',
        'pointermove',
        'pointermissed',
        'pointercancel',
        'wheel',
      ],
    },
    {
      directive: NgtElementEvents,
      outputs: ['attached', 'updated', 'created', 'disposed'],
    },
  ],
})
export class PokerDice {
  protected readonly Math = Math;

  options = input({} as Partial<NgtThreeElements['ngt-group']>);

  modelRef = viewChild<ElementRef<Group>>('model');

  protected gltf = gltfResource<PokerDiceGLTFGLTFResult>(() => PokerDiceGLTF);

  constructor() {
    extend({ Group, Mesh });

    const objectEvents = inject(NgtObjectEvents, { host: true });
    const elementEvents = inject(NgtElementEvents, { host: true });

    objectEvents.events.set(this.modelRef);
    elementEvents.events.set(this.modelRef);
  }
}
